# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\x05vc.v2\"\xca\x02\n\x15VoiceConversionConfig\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x35\n\x07payload\x18\x02 \x01(\x0b\x32$.vc.v2.VoiceConversionConfig.Payload\x1aX\n\tAudioInfo\x12\x13\n\x0bsample_rate\x18\x01 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x02 \x01(\x05\x12\x0c\n\x04\x62its\x18\x03 \x01(\x05\x12\x16\n\x0e\x61udio_encoding\x18\x04 \x01(\t\x1a\x91\x01\n\x07Payload\x12\r\n\x05voice\x18\x01 \x01(\t\x12:\n\ninput_info\x18\x02 \x01(\x0b\x32&.vc.v2.VoiceConversionConfig.AudioInfo\x12;\n\x0boutput_info\x18\x03 \x01(\x0b\x32&.vc.v2.VoiceConversionConfig.AudioInfo\"e\n\x12StreamingVCRequest\x12.\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1c.vc.v2.VoiceConversionConfigH\x00\x12\x14\n\naudio_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07request\"Z\n\x14VoiceConversionState\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x05\x12\x13\n\x0bstatus_text\x18\x04 \x01(\t\"e\n\x13StreamingVCResponse\x12,\n\x05state\x18\x01 \x01(\x0b\x32\x1b.vc.v2.VoiceConversionStateH\x00\x12\x14\n\naudio_data\x18\x02 \x01(\x0cH\x00\x42\n\n\x08response2[\n\x0fVoiceConversion\x12H\n\x0bStreamingVC\x12\x19.vc.v2.StreamingVCRequest\x1a\x1a.vc.v2.StreamingVCResponse(\x01\x30\x01\x42\x1e\n\x1c\x63om.mthreads.ai.protos.vc.v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034com.mthreads.ai.protos.vc.v2'
  _globals['_VOICECONVERSIONCONFIG']._serialized_start=31
  _globals['_VOICECONVERSIONCONFIG']._serialized_end=361
  _globals['_VOICECONVERSIONCONFIG_AUDIOINFO']._serialized_start=125
  _globals['_VOICECONVERSIONCONFIG_AUDIOINFO']._serialized_end=213
  _globals['_VOICECONVERSIONCONFIG_PAYLOAD']._serialized_start=216
  _globals['_VOICECONVERSIONCONFIG_PAYLOAD']._serialized_end=361
  _globals['_STREAMINGVCREQUEST']._serialized_start=363
  _globals['_STREAMINGVCREQUEST']._serialized_end=464
  _globals['_VOICECONVERSIONSTATE']._serialized_start=466
  _globals['_VOICECONVERSIONSTATE']._serialized_end=556
  _globals['_STREAMINGVCRESPONSE']._serialized_start=558
  _globals['_STREAMINGVCRESPONSE']._serialized_end=659
  _globals['_VOICECONVERSION']._serialized_start=661
  _globals['_VOICECONVERSION']._serialized_end=752
# @@protoc_insertion_point(module_scope)
