# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import service_pb2 as proto_dot_service__pb2


class VoiceConversionStub(object):
    """Service that implements VC API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamingVC = channel.stream_stream(
                '/vc.v2.VoiceConversion/StreamingVC',
                request_serializer=proto_dot_service__pb2.StreamingVCRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.StreamingVCResponse.FromString,
                )


class VoiceConversionServicer(object):
    """Service that implements VC API.
    """

    def StreamingVC(self, request_iterator, context):
        """Convert the input speech to a given voice
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceConversionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamingVC': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamingVC,
                    request_deserializer=proto_dot_service__pb2.StreamingVCRequest.FromString,
                    response_serializer=proto_dot_service__pb2.StreamingVCResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vc.v2.VoiceConversion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VoiceConversion(object):
    """Service that implements VC API.
    """

    @staticmethod
    def StreamingVC(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/vc.v2.VoiceConversion/StreamingVC',
            proto_dot_service__pb2.StreamingVCRequest.SerializeToString,
            proto_dot_service__pb2.StreamingVCResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
